Repository openedx/cc2olx, pull requests merged in 2021-01, with the labels that each got.

#32 Add 'formatting' tox environment
  .travis.yml
  src/cc2olx/tools/video_upload.py
  tests/conftest.py
  tests/test_tools.py
Labels: changes requested, open-source-contribution

#29 Fix deprecation warnings, add log statements
  src/cc2olx/filesystem.py
  src/cc2olx/main.py
  src/cc2olx/models.py
  src/cc2olx/qti.py
Labels: open-source-contribution, waiting on author

#24 [BD-27] [TNL-7664] [BB-3166] Add a way to support third party video as xblocks
  README.rst
  src/cc2olx/cli.py
  src/cc2olx/iframe_link_parser.py
  src/cc2olx/link_file_reader.py
  src/cc2olx/main.py
  src/cc2olx/olx.py
  src/cc2olx/settings.py
  tests/conftest.py
  tests/fixtures_data/imscc_file/iframe.html
  tests/fixtures_data/imscc_file/imsmanifest.xml
  tests/fixtures_data/link_map.csv
  tests/fixtures_data/studio_course_xml/course.xml
  tests/test_cli.py
  tests/test_kaltura_link_parser.py
  tests/test_link_file_reader.py
  tests/test_main.py
  tests/test_models.py
  tests/test_olx.py
  tests/test_settings.py
Labels: blended, needs triage

#36 [BB-3540] [BD-27] [TNL-7890] Investigate PDF issues in Common Cartridge Course Conversions
  src/cc2olx/main.py
  src/cc2olx/models.py
  tests/fixtures_data/imscc_file/extra_files/example.pdf
  tests/fixtures_data/imscc_file/imsmanifest.xml
  tests/fixtures_data/studio_course_xml/course.xml
  tests/test_main.py
  tests/test_models.py
Labels: blended, needs triage
